name: Bionic Tech Store CI/CD

on:
  push:
    branches: [ "main", "feature/sensors-desc" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./bionic-tech-store[cite: 4]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4[cite: 4]

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20[cite: 4]

      - name: Install dependencies
        run: npm install[cite: 4]

      - name: Build project
        run: npm run build[cite: 4]